@startuml .
skinparam classAttributeIconSize 0
class library {
 -会員番号（学生証番号／職員番号）
  -会員情報
  -メールアドレス
 -図書
  -書名
  -管理番号
  -種別 (図書／雑誌)
  -状態 (貸出中／返却済)
- 貸出
  - 会員番号
  - 貸出日
  - 返却期限日
  - 返却期限日
  - 貸出履歴
- 予約
  - 予約日
  - 状態（有効／取消）
  - 予約カード
  - 予約日
  - 予約履歴
  - 状態（有効／取消）
+ 予約受け付ける()
+ 図書を貸し出す／返却する()
+ 履歴を記録する()
+ 履歴を閲覧する()
}
@enduml
