@startuml 図書館システムドメインモデル図
skinparam componentStyle rectangle

' 会員関連
[会員] <|-- [学生]
[会員] <|-- [教職員]
[会員] o-- [会員番号]
[会員] o-- [氏名]
[会員] o-- [メールアドレス]

' 図書関連
[図書] <|-- [書籍]
[図書] <|-- [雑誌]
[図書] o-- [管理番号]
[図書] o-- [書名]

' 貸出関連
[貸出] o-- [貸出日]
[貸出] o-- [返却日]
[貸出] --> [会員]
[貸出] --> [図書]

' 予約関連
[予約] o-- [予約日]
[予約] --> [会員]
[予約] --> [図書]

@enduml
