@startuml
skinparam classAttributeIconSize 0
class RoboDog {
・属性
 -myName: String
 -myTime: int
 -goodMorning: String
 -goodAfternoon: String
 -goodNight: String
 -firstValue: int
 -secondValue: int
 
 -result: int
 ・操作
 +getMyname(): String
 +setNewName(): int
 +setNewTime(): void
 +getMyGreeting(): String
 +setFirstValue(): void
 +setSecondValue(): void
 +getAddition(): int
}

@enduml
